name: Emma Barone Artist
favicon: null
layout_spectrum: 0.98916
typography_spectrum: 0.26259
title: 'Contemporary Visual Artist '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000004'
    - '#fefffa'
    - '#acc5bf'
    - '#4b7585'
    - '#6a3813'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
